- name: Add credential store to global gitconfig
  community.general.git_config:
    name: credential.helper
    scope: global
    value: store
  when: 
    - GIT_USER is defined
    - GIT_TOKEN is defined
    - HTCONDOR_CONFIG_GIT_REPO is defined

- name: Add git credentials
  vars:
    GIT_PROTOCOL: "{{ HTCONDOR_CONFIG_GIT_REPO | urlsplit('scheme') }}"
    GIT_HOST: "{{ HTCONDOR_CONFIG_GIT_REPO | urlsplit('hostname') }}"
    GIT_PORT: "{{ HTCONDOR_CONFIG_GIT_REPO | urlsplit('port') }}"
  template:
    src: git-credentials.j2
    dest: "{{ ansible_env.HOME }}/.git-credentials"
    mode: 0600
  when: 
    - GIT_USER is defined
    - GIT_TOKEN is defined
    - HTCONDOR_CONFIG_GIT_REPO is defined
