- name: Get pool password file
  shell: "condor_config_val SEC_PASSWORD_FILE"
  register: SEC_PASSWORD_FILE

- name: Add directory for the pool password
  file:
    path: "{{ SEC_PASSWORD_FILE.stdout | dirname }}"
    recurse: yes
    state: directory
    mode: 0755

- name: Add HTCondor Pool Password
  copy:
    dest: "{{ SEC_PASSWORD_FILE.stdout }}"
    content: "{{ HTCONDOR_POOL_PASSWORD }}"
    mode: 0600

#- name: Add HTCondor Pool Password
#  vars:
#    ansible_python_interpreter: /usr/bin/python3
#  expect:
#    command: /bin/bash -c "condor_store_cred add -c -f {{ SEC_PASSWORD_FILE.stdout }}"
#    responses:
#      "Enter password:": "{{ HTCONDOR_POOL_PASSWORD }}"
