- name: Get token system directory
  command: "condor_config_val SEC_TOKEN_SYSTEM_DIRECTORY"
  register: SEC_TOKEN_SYSTEM_DIRECTORY
  changed_when: SEC_TOKEN_SYSTEM_DIRECTORY.rc == 0

- name: Normalize token system directory to always have a trailing slash
  set_fact:
    normalized_sec_token_system_directory: "{{ SEC_TOKEN_SYSTEM_DIRECTORY.stdout.rstrip('/') }}/"

- name: Get token directory
  command: "condor_config_val SEC_TOKEN_DIRECTORY"
  register: SEC_TOKEN_DIRECTORY
  changed_when: SEC_TOKEN_DIRECTORY.rc == 0

- name: Normalize token directory to always have a trailing slash
  set_fact:
    normalized_sec_token_directory: "{{ SEC_TOKEN_DIRECTORY.stdout.rstrip('/') }}/"

- name: Get token password directory
  command: "condor_config_val SEC_PASSWORD_DIRECTORY"
  register: SEC_PASSWORD_DIRECTORY
  changed_when: SEC_PASSWORD_DIRECTORY.rc == 0

- name: Normalize password directory to always have a trailing slash
  set_fact:
    normalized_sec_password_directory: "{{ SEC_PASSWORD_DIRECTORY.stdout.rstrip('/') }}/"

- name: Add directory for token passwords
  file:
    path: "{{ normalized_sec_password_directory }}"
    recurse: yes
    state: directory
    mode: 0700
  when:
    - HTCONDOR_TOKEN_PASSWORD is defined

- name: Add system directory for tokens
  file:
    path: "{{ normalized_sec_token_system_directory }}"
    recurse: yes
    state: directory
    mode: 0700
  when:
    - HTCONDOR_TOKEN is defined
    - normalized_sec_token_system_directory | length > 0

- name: Add directory for tokens
  file:
    path: "{{ normalized_sec_token_directory }}"
    recurse: yes
    state: directory
    mode: 0700
  when:
    - HTCONDOR_TOKEN is defined
    - normalized_sec_token_directory | length > 0

- name: Add tokens to directory
  vars:
    directories:
      - "{{ normalized_sec_token_system_directory }}"
      - "{{ normalized_sec_token_directory }}"
  include_tasks: add_token.yaml
  loop: "{{ HTCONDOR_TOKEN | dict2items | product(directories)|list }}"
  loop_control:
    label: "Adding tokens to {{ item[1] }}"
  when:
    - HTCONDOR_TOKEN is defined
    - item[1] | length > 0

- name: Add token passwords to directory
  include_tasks: add_token_password.yaml
  loop: "{{ HTCONDOR_TOKEN_PASSWORD | dict2items }}"
  loop_control:
    label: "Adding token password to {{ normalized_sec_password_directory + item.key }}"
  when:
    - HTCONDOR_TOKEN_PASSWORD is defined
    - item.key | length > 0
